config/routes.rb
Rails.application.routes.draw do
  root 'memoirs#index'
  devise_for :users

  resources :memoirs, except: [:destroy, :edit, :update]

  resources :neighborhoods, only: [:index, :show] do
    resources :memoirs, only: [:index]
  end

end

app/models/memoir.rb
class Memoir < ActiveRecord::Base
  belongs_to :neighborhood

  validates :name, presence: true
  validates :age, presence: true
  validates :memoir, presence: true
  validates :neighborhood_id, presence: true

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base

  NEIGHBORHOODS = [
    "Allston",
    "Back Bay",
    "Bay Village",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dorchester",
    "Downtown",
    "East Boston",
    "Fenway Kenmore",
    "Hyde Park",
    "Jamaica Plain",
    "Mattapan",
    "Mission Hill",
    "North End",
    "Roslindale",
    "Roxbury",
    "South Boston",
    "South End",
    "West End",
    "West Roxbury"
  ]

  has_many :memoirs

  validates :name, inclusion: { in: NEIGHBORHOODS }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/memoirs_controller.rb
class MemoirsController < ApplicationController
  def index
    if params[:query] == nil || params[:query].match(/^\s*$/)
      @memoirs = Memoir.order("random()")
    elsif params[:query].split.size == 1
      @memoirs = Memoir.where("memoir ILIKE '%#{params[:query]}%' OR name ILIKE '%#{params[:query]}%'")
    elsif params[:query].split.size >= 2
      split_query = params[:query].split
      mapped_split_query = split_query.map { |word| "(memoir ILIKE '%#{word}%' OR name ILIKE '%#{word}%') AND " }
      formatted_query = mapped_split_query.inject(:+).rpartition(" AND ").first
      @memoirs = Memoir.where(formatted_query)
    end
  end

  def show
    @memoir = Memoir.find(params[:id])
  end

  def new
    @memoir = Memoir.new
  end

  def create
    @memoir = Memoir.new(memoir_params)
    if @memoir.save
      redirect_to memoir_path(@memoir)
    else
      render :new
    end
  end

  def search
    if params[:search] == nil
      render :index
    else
      @memoirs = Memoir.where("memoir ILIKE '%#{params[:search]}%'")
      redirect_to root_path
    end
  end

  protected

  def memoir_params
    params.require(:memoir).permit(:name, :age, :memoir, :neighborhood_id)
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.all
  end

  def show
    @neighborhood = Neighborhood.find(params[:id])

    if @neighborhood.memoirs.empty?
      flash[:notice] = "No memoirs for that neighborhood yet"
      redirect_to neighborhoods_path
    else
      @memoirs = @neighborhood.memoirs
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
  <title>Six Word Memoirs</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1 class="nav-heading"><a href="/">Six Word Memoirs</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right memoir-text">
        <li>
          <%= form_tag("/", method: "get") do %>
            <%= text_field_tag(:query, nil, required: true, value: "Search", class: "radius") %>
          <% end %>
        </li>
        <li><%= link_to "Random", memoir_path(Memoir.all.sample) %></li>
        <li><%= link_to "Neighborhoods", neighborhoods_path %></li>
        <li><%= link_to "Submit", new_memoir_path %></li>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/memoirs/index.html.erb
<div class="small-10 medium-12 large-12 small-centered columns text-center">

  <%= link_to root_path do %>
    <h1 class="text-center heading animated pulse">Six Word Memoirs</h1>
  <% end %>



  <div class="row">
    <% @memoirs.each do |memoir| %>
      <p class="animated fadeIn memoirs memoir-text"><%= link_to memoir_path(memoir) do %><%= memoir.memoir %><br>
        <%= memoir.name %>, <%= memoir.age %>, <%= memoir.neighborhood.name %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/memoirs/new.html.erb
<div class="small-10 medium-12 large-12 small-centered columns text-center">

<% if @memoir.errors.any? %>
    <div id="error_explanation">
      <h2 class="memoir-text">
        Please fix
        <%= pluralize(@memoir.errors.count, "error") %>:
      </h2>
      <p class="memoir-text">
        <% @memoir.errors.full_messages.each do |msg| %>
        <%= msg %><br>
        <% end %>
      </p>
    </div>
<% end %>

  <h1 class="text-center heading animated pulse">Submit Your Memoir</h1>

  <div class="small-10 medium-8 large-4 small-centered columns text-center">

    <div class="text-left animated fadeIn">

        <%= form_for @memoir do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, class: "radius" %>

          <%= f.label :age %>
          <%= f.text_field :age, class: "radius" %>

          <%= f.label :memoir, "Six Word Memoir" %>
          <%= f.text_field :memoir, class: "radius" %>

          <%= f.label :neighborhood_id %>
          <%= f.select :neighborhood_id, Neighborhood.all.map { |n| [n.name, n.id] }, { }, { class: "chosen-select" } %>
          
          <%= f.submit "Submit Your Memoir",  :class => 'button radius' %>
        <% end %>
    </div>

  </div>

</div>

app/views/memoirs/show.html.erb
<div class="small-12 medium-11 large-10 small-centered columns text-center animated fadeIn">
  <p class="show">
    <h1 class="memoir-text-show"><%= @memoir.memoir %></h1>
    <h1 class="memoir-text-subhead"><%= @memoir.name %>, <%= @memoir.age %>, <%= @memoir.neighborhood.name %></h1>
  </p>
</div>

app/views/neighborhoods/index.html.erb
<div class="small-10 medium-12 large-12 small-centered columns text-center">

  <h1 class="text-center heading animated pulse">Neighborhoods</h1>

  <div class="row">
    <% @neighborhoods.each do |n| %>
      <p class="animated fadeIn memoirs memoir-text"><%= link_to n.name, neighborhood_path(n) %></p>
    <% end %>
  </div>
</div>

app/views/neighborhoods/show.html.erb
<div class="small-10 medium-9 large-8 small-centered columns text-center">

    <h1 class="text-center heading animated pulse"><%= @neighborhood.name %> Memoirs</h1>
    <% @memoirs.each do |memoir| %>
      <p class="memoirs animated fadeIn memoir-text"><%= link_to memoir_path(memoir) do%><%= memoir.memoir %><br>
        <%= memoir.name %>, <%= memoir.age %>, <%= memoir.neighborhood.name %>
        <% end %>
      </p>
        </div>
    <% end %>

</div>